# Generated by Django 2.1.3 on 2018-11-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsocprofile',
            name='lsoc_permissions',
        ),
        migrations.AddField(
            model_name='lsocprofile',
            name='lsoc_permissions',
            field=models.ManyToManyField(to='project01.LSOCPermission'),
        ),
    ]
