# Generated by Django 2.1.3 on 2018-11-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0003_auto_20181110_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsocprofile',
            name='lsoc_permissions',
        ),
        migrations.AddField(
            model_name='lsocprofile',
            name='lsoc_permissions',
            field=models.TextField(default='*'),
        ),
        migrations.DeleteModel(
            name='LSOCPermission',
        ),
    ]
