# Generated by Django 2.1.3 on 2018-11-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0004_auto_20181110_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsocprofile',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
