# Generated by Django 2.1.3 on 2018-11-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0006_mqttsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MQTTSettings',
            new_name='MQTTConfig',
        ),
    ]
