# Generated by Django 2.1.3 on 2019-02-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0008_auto_20181117_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttconfig',
            name='ip',
            field=models.CharField(max_length=500),
        ),
    ]
