# Generated by Django 2.2.4 on 2019-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0009_auto_20190218_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsocprofile',
            name='lsoc_permissions',
            field=models.TextField(default=dict),
        ),
    ]
