# Generated by Django 2.2.4 on 2019-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0010_auto_20190824_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
