# Generated by Django 2.2.5 on 2019-09-22 15:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0011_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsocprofile',
            name='lsoc_permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
