# Generated by Django 3.0.1 on 2019-12-27 09:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0012_auto_20190922_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsocprofile',
            name='lsoc_permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
